# Generated by Django 5.0 on 2026-01-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='triage_state',
            field=models.JSONField(default=dict),
        ),
    ]
